// <auto-generated />
using EFCoreSqliteDemo.Models.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCoreSqliteDemo.Migrations
{
    [DbContext(typeof(WorkingDbContext))]
    [Migration("20171105075357_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentName");

                    b.Property<int>("PDepartmentID");

                    b.HasKey("ID");

                    b.HasIndex("PDepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DepartmentID");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("RoleID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.WorkItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("Memos");

                    b.Property<DateTime>("RecordDate");

                    b.Property<string>("WorkContent");

                    b.HasKey("ID");

                    b.HasIndex("CreateUserID");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.Department", b =>
                {
                    b.HasOne("EFCoreSqliteDemo.Models.DataModel.Department", "PDepartment")
                        .WithMany()
                        .HasForeignKey("PDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.User", b =>
                {
                    b.HasOne("EFCoreSqliteDemo.Models.DataModel.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EFCoreSqliteDemo.Models.DataModel.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCoreSqliteDemo.Models.DataModel.WorkItem", b =>
                {
                    b.HasOne("EFCoreSqliteDemo.Models.DataModel.User", "CreateUser")
                        .WithMany("WorkItems")
                        .HasForeignKey("CreateUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
